package org.guriytan.downloader.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import org.guriytan.downloader.entity.DownloadTask;

import org.guriytan.downloader.dao.DownloadTaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadTaskDaoConfig;

    private final DownloadTaskDao downloadTaskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadTaskDaoConfig = daoConfigMap.get(DownloadTaskDao.class).clone();
        downloadTaskDaoConfig.initIdentityScope(type);

        downloadTaskDao = new DownloadTaskDao(downloadTaskDaoConfig, this);

        registerDao(DownloadTask.class, downloadTaskDao);
    }
    
    public void clear() {
        downloadTaskDaoConfig.clearIdentityScope();
    }

    public DownloadTaskDao getDownloadTaskDao() {
        return downloadTaskDao;
    }

}
